### ISSUE TITLE
Can't add "Score Summary" to problem

### ISSUE THREAD

**Issue by chrisndodge** [open-craft/problem-builder#118]
Hello @mtyaka @jbzdak,

I've been trying out the problem-build/step-builder on my instance of Open edX (tip of master as of July 18th, 2016).

I can't seem to add the "Score Summary" to the end of an assessment, at the Review Step. If I click the button, it just greys out, but nothing happens. I don't see any Network calls in my Chrome Developer tools on the button click. I also don't see any JS errors in the console.

Here's a screen grab:

![screen shot 2016-07-21 at 4 45 42 pm](https://cloud.githubusercontent.com/assets/2362917/17038315/345f22b4-4f63-11e6-8cf4-1458398e468e.png)

I'm just using Problem Builder for the first time, so perhaps I'm doing something wrong. If I get a chance, I'll try hooking up a JS debugger and stepping through the code.

Thanks,

Chris

**Comment by mtyaka** [comment]
@chrisndodge Thanks for reporting this! We will look into it. /cc @bradenmacdonald

**Comment by mtyaka** [comment]
@chrisndodge I was able to reproduce the issue. It happens with some other buttons that are conditionally disabled as well. It looks like something must have changed in edx-platform recently that's causing this.

The problem seems to be the lines that disable the button on click: https://github.com/edx/xblock-utils/blob/817791ed16fe027e88b62237643c3c469fddb32d/xblockutils/public/studio_container.js#L15-L18

That click even handler runs first, and after it disables the button, no other event handlers are run. I don't know why that is... I assume there's some JS code in edx-platform that globally stops event propagation on disabled buttons or something, but I couldn't find it. Or perhaps the order in which event handlers are attached has changed at some point.

The buttons are not `<button>` elements but `<a>` elements and I don't think `<a>` elements even support the `disabled` property.

I commented out this line to make the buttons work correctly: https://github.com/edx/xblock-utils/blob/817791ed16fe027e88b62237643c3c469fddb32d/xblockutils/public/studio_container.js#L17
However that's probably not the ideal fix, especially since `<a>` element "buttons" have been replaced with actual `<button>` elements in edx-platform and we should probably do the same in problem-builder, after which setting the `disabled` property will make sense.

I believe the proper fix would be to get the xblockutils function that disables the button run *after* the function that adds the component (which happens here: https://github.com/edx/edx-platform/blob/e8c60bc6c1ccf785d493235a11c1538a0c55b194/cms/static/js/views/components/add_xblock.js#L59-L74).

**Comment by eliangcs** [comment]
@mtyaka I would like to fix this issue but I'm new to edx-platform project. Do you mind providing me some background and guidance for me to get started with this issue? cc: @antoviaque @bradenmacdonald

**Comment by bradenmacdonald** [comment]
@eliangcs Great! @mtyaka just left on vacation, but I'll see if I can find someone else to help you out. You can also join us on Slack, if you're not there already.

**Comment by bradenmacdonald** [comment]
@eliangcs Actually, there is already some background above... Basically you need to setup an edx devstack, then clone xblock-utils and problem-builder into the devstack "src" folder and install each one into the edxapp virtualenv with something like `~/venvs/edxapp/bin/pip install -e /edx/src/xblock-utils` and `~/venvs/edxapp/bin/pip install -e /edx/src/problem-builder`; then run Studio and make edits to the xblock-utils code until the problem is fixed. Then open a PR to submit your changes to xblock-utils and ping us on it.

**Comment by eliangcs** [comment]
@bradenmacdonald thanks for you instruction! I was able to set up my devstack and debug. I just sent a PR to xblock-utils fixing this issue. The solution is basically what @mtyaka proposed. CC: @antoviaque
