### ISSUE TITLE
Use Dashboard for a series of Long Answers

### ISSUE THREAD

**Issue by danielmcquillen** [open-craft/problem-builder#126]
Is there a way to utilize the pb-dashboard plugin to just show a simple visualization of which of a series of Long Answers has been submitted?

e.g. the user has five Long Answers to submit, and can refer to a simple graphic to see how many steps (e.g. answers) they've gone so far.

**Comment by antoviaque** [comment]
@danielmcquillen The dashboard XBlock currently only works with MCQs, see the doc at https://github.com/open-craft/problem-builder/blob/master/doc/Dashboard.md and the code https://github.com/open-craft/problem-builder/blob/0ff0610790c47641a72ec9ef0c8e84a4d0707c09/problem_builder/dashboard.py#L340

It wouldn't be too much of a stretch to extend it to cover your use case, to lookup completion/grade on other types of XBlocks, rather than MCQs' values, but that would still need to be implemented. We can help with that though, if you want.
