### ISSUE TITLE
ID of answer in event?

### ISSUE THREAD

**Issue by danielmcquillen** [open-craft/problem-builder#148]
Currently problem-builder sends an event through the Open edX event structure when a long form answer is submitted, which is great.

That event has an event_type `xblock.problem_builder.submitted` and includes an `event` property that looks like this:

```
{
    ... some basic event properties ...
 
   "event": {
        "submitted_answer": {
            "example-long-form-question": [
                {
                    "name": "input",
                    "value": "Some kind of input by student."
                }
            ]
        },
        "num_attempts": 0,
        "grade": 1.0
    },
  
   ... some context info...
}
```

Is there a way to get the event to include the id of the answer as stored in the `id` column of the `problem_builder_answer` table in MySQL?

I have a feeling a small adjustment could be made somewhere around line 704 in mentoring.py to capture the id of the saved submission, but it's not entirely clear to me.

Thanks for any thoughts!

**Comment by bradenmacdonald** [comment]
Hi @danielmcquillen , that makes sense to me, and although I haven't investigated this in detail just now, I do think it should be possible to make that work with a small change. Would you be able to give it a shot and open a PR?

**Comment by danielmcquillen** [comment]
@bradenmacdonald sure thing. Am I right in assuming that after the child.save() operation, that child object should have an "id" property? https://github.com/open-craft/problem-builder/blob/master/problem_builder/mentoring.py#L701

**Comment by bradenmacdonald** [comment]
@danielmcquillen  Oh, I see - I assumed that when you said `id` you meant `name`... We don't actually use the `id` for anything directly - the combination of `('student_id', 'course_key', 'name'),` is guaranteed to be unique and since it functions as a compound primary key, it's what we usually use for lookups etc. What's your use case for needing `id`?

**Comment by danielmcquillen** [comment]
We're listening for events on a separate system, and want to include the id of the answer in that event so we can retrieve it from the database. As of now, the id isn't included in the information sent with the event.

**Comment by bradenmacdonald** [comment]
Well, I think that the current event contains the student's username, course key, and the answer `name`, so with the right SQL it's possible to retrieve the data you need - something like `SELECT * FROM problem_builder_answer pba, auth_user u WHERE student_id=u.id AND u.username=(event.username) AND pba.course_key=(event.course_key) AND pba.name=(event.submitted_answer.....name) LIMIT 1`

... but I also don't think it would hurt anything to include the answer ID directly in the event - I'm just a bit reluctant because we only use `name` in the code, and part of that is to make it clear that multiple `Answer` blocks can be configured to share the same `name` and thus share the same student response. If we focus on the `id`, it may be less obvious that other XBlocks in the course may have the same numeric answer ID for their Answer entry, if they were configured with the same `name`. That's a minor concern though.

**Comment by danielmcquillen** [comment]
Ah, ok. I can use those three pieces of info to uniquely identify a name. So no need for id in the event! I'll close this issue. Thanks @bradenmacdonald !
