### ISSUE TITLE
Student can change answer in Problem-Builder after Subsection due date passed

### ISSUE THREAD

**Issue by danielmcquillen** [open-craft/problem-builder#169]
Apologies if this isn't a bug and I'm somehow missing a configuration step or otherwise.

I have a due date set in a subsection, which has passed:

![image](https://user-images.githubusercontent.com/119496/30944038-9f78c584-a438-11e7-9950-c8785778e134.png)

In this subsection I have a problem-builder xblock (configured as long answer). Even though the due date has passed, I can still log in as my 'student' user and change my answer. 

Shouldn't problem-builder disallow changes after the due date has passed? 

Thanks for your help!

**Comment by bradenmacdonald** [comment]
@danielmcquillen Hmm, I haven't had a chance to look into this yet, but off the top of my head, I don't think there's any code in Problem Builder that is designed to support this functionality - so I doubt it's a bug, but it may be a missing feature.

Do normal capa problems disallow changes after the due date has passed?

**Comment by danielmcquillen** [comment]
@bradenmacdonald thanks. Yes, did a quick check with a pulldown and it was disabled after the course end date passed. Not sure about other XBlocks.
In the meantime, we'll just go through and turn off the submit button once the course end date has passed.

**Comment by antoviaque** [comment]
@danielmcquillen Since @bradenmacdonald went on holidays this week I'll reply - sorry for the delay.

That's definitely a possible workaround, thanks for sharing. Braden is correct, that we would need to add support for this functionality - it's a bug in the sense that it doesn't behave consistently with the other XBlocks on this, but we could only work on this if someone could pay for the time to develop support for this. 

We can try to keep it in mind for future work related to Problem Builder, in case we get a chance to work on this within the scope of another project, but that's without guarantee. Or if you want to ensure this is worked on, you could either prepare and send a patch, or contract us to do it.
